New log file opened at Fri May 01 18:56:17 CEST 2015 by 5756@Felix-PC
Taking next connection to: 52750
New client attempting to connect on port: 52754-52750
  Address = /192.168.178.33:52750
This client on port 52754 has uuid 56c3a132-d24e-40d9-9152-396b9a8fecc5 configName activator humanReadableName Activator protocolVersion 1 featureTags Vector()
Connected Clients: activator-56c3a132-d24e-40d9-9152-396b9a8fecc5
Taking next connection to: 52750
New client attempting to connect on port: 52755-52750
  Address = /192.168.178.33:52750
Handshake exception on socket: 52755
sbt.impl.ipc.HandshakeException: Unable to perform handshake
	at sbt.impl.ipc.Peer.handshake(IPC.scala:46)
	at sbt.impl.ipc.MultiClientServer.<init>(IPC.scala:150)
	at sbt.server.SbtServerSocketHandler$$anon$1.run(SbtServerSocketHandler.scala:43)
Caused by: java.net.SocketException: Software caused connection abort: recv failed
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.read(Unknown Source)
	at java.net.SocketInputStream.read(Unknown Source)
	at java.io.BufferedInputStream.fill(Unknown Source)
	at java.io.BufferedInputStream.read(Unknown Source)
	at java.io.DataInputStream.readInt(Unknown Source)
	at sbt.impl.ipc.Peer.receive(IPC.scala:95)
	at sbt.impl.ipc.Peer.handshake(IPC.scala:49)
	... 2 more
Taking next connection to: 52750
New client attempting to connect on port: 52756-52750
  Address = /192.168.178.33:52750
This client on port 52756 has uuid 2c834c8e-978b-490a-affe-141cf2c3c28d configName activator humanReadableName Activator protocolVersion 1 featureTags Vector()
Connected Clients: activator-56c3a132-d24e-40d9-9152-396b9a8fecc5, activator-2c834c8e-978b-490a-affe-141cf2c3c28d
Taking next connection to: 52750
New client attempting to connect on port: 52977-52750
  Address = /192.168.178.33:52750
Handshake exception on socket: 52977
sbt.impl.ipc.HandshakeException: Unable to perform handshake
	at sbt.impl.ipc.Peer.handshake(IPC.scala:46)
	at sbt.impl.ipc.MultiClientServer.<init>(IPC.scala:150)
	at sbt.server.SbtServerSocketHandler$$anon$1.run(SbtServerSocketHandler.scala:43)
Caused by: java.net.SocketException: Software caused connection abort: recv failed
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.read(Unknown Source)
	at java.net.SocketInputStream.read(Unknown Source)
	at java.io.BufferedInputStream.fill(Unknown Source)
	at java.io.BufferedInputStream.read(Unknown Source)
	at java.io.DataInputStream.readInt(Unknown Source)
	at sbt.impl.ipc.Peer.receive(IPC.scala:95)
	at sbt.impl.ipc.Peer.handshake(IPC.scala:49)
	... 2 more
Taking next connection to: 52750
New client attempting to connect on port: 52979-52750
  Address = /192.168.178.33:52750
This client on port 52979 has uuid 969a3922-d7aa-4cac-b234-7a2511baa12c configName play-fork-run humanReadableName Play Fork Run protocolVersion 1 featureTags Vector()
Connected Clients: activator-2c834c8e-978b-490a-affe-141cf2c3c28d, play-fork-run-969a3922-d7aa-4cac-b234-7a2511baa12c
Taking next connection to: 52750
Checking to see if clients are empty...
We have 1 non-daemon clients, continuing serving connections.
Taking next connection to: 52750
Checking to see if clients are empty...
We have 1 non-daemon clients, continuing serving connections.
Taking next connection to: 52750
