New log file opened at Fri May 01 14:55:56 CEST 2015 by 2088@ArifCerit
Taking next connection to: 61445
New client attempting to connect on port: 61446-61445
  Address = /192.168.2.102:61445
This client on port 61446 has uuid 39639325-a470-42e7-96d4-86c23012983e configName activator humanReadableName Activator protocolVersion 1 featureTags Vector()
Connected Clients: activator-39639325-a470-42e7-96d4-86c23012983e
Taking next connection to: 61445
New client attempting to connect on port: 61447-61445
  Address = /192.168.2.102:61445
Handshake exception on socket: 61447
sbt.impl.ipc.HandshakeException: Unable to perform handshake
	at sbt.impl.ipc.Peer.handshake(IPC.scala:46)
	at sbt.impl.ipc.MultiClientServer.<init>(IPC.scala:150)
	at sbt.server.SbtServerSocketHandler$$anon$1.run(SbtServerSocketHandler.scala:43)
Caused by: java.net.SocketException: Software caused connection abort: recv failed
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(Unknown Source)
	at java.net.SocketInputStream.read(Unknown Source)
	at java.net.SocketInputStream.read(Unknown Source)
	at java.io.BufferedInputStream.fill(Unknown Source)
	at java.io.BufferedInputStream.read(Unknown Source)
	at java.io.DataInputStream.readInt(Unknown Source)
	at sbt.impl.ipc.Peer.receive(IPC.scala:95)
	at sbt.impl.ipc.Peer.handshake(IPC.scala:49)
	... 2 more
Taking next connection to: 61445
New client attempting to connect on port: 61448-61445
  Address = /192.168.2.102:61445
This client on port 61448 has uuid 00c0226b-e88c-4897-b72e-726df27c78c6 configName activator humanReadableName Activator protocolVersion 1 featureTags Vector()
Connected Clients: activator-39639325-a470-42e7-96d4-86c23012983e, activator-00c0226b-e88c-4897-b72e-726df27c78c6
Taking next connection to: 61445
Checking to see if clients are empty...
We have 1 non-daemon clients, continuing serving connections.
Taking next connection to: 61445
