New log file opened at Sat May 02 20:38:38 CEST 2015 by 2752@Felix-PC
Taking next connection to: 49506
New client attempting to connect on port: 49513-49506
  Address = /192.168.178.33:49506
This client on port 49513 has uuid dda06fbc-939d-42c9-8657-5998717df780 configName activator humanReadableName Activator protocolVersion 1 featureTags Vector()
Connected Clients: activator-dda06fbc-939d-42c9-8657-5998717df780
Taking next connection to: 49506
New client attempting to connect on port: 49515-49506
  Address = /192.168.178.33:49506
Handshake exception on socket: 49515
sbt.impl.ipc.HandshakeException: Unable to perform handshake
	at sbt.impl.ipc.Peer.handshake(IPC.scala:46)
	at sbt.impl.ipc.MultiClientServer.<init>(IPC.scala:150)
	at sbt.server.SbtServerSocketHandler$$anon$1.run(SbtServerSocketHandler.scala:43)
Caused by: java.net.SocketException: Software caused connection abort: recv failed
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.read(Unknown Source)
	at java.net.SocketInputStream.read(Unknown Source)
	at java.io.BufferedInputStream.fill(Unknown Source)
	at java.io.BufferedInputStream.read(Unknown Source)
	at java.io.DataInputStream.readInt(Unknown Source)
	at sbt.impl.ipc.Peer.receive(IPC.scala:95)
	at sbt.impl.ipc.Peer.handshake(IPC.scala:49)
	... 2 more
Taking next connection to: 49506
New client attempting to connect on port: 49516-49506
  Address = /192.168.178.33:49506
This client on port 49516 has uuid 93f84cf2-9e6a-48cb-a420-a57e5535aeb5 configName activator humanReadableName Activator protocolVersion 1 featureTags Vector()
Connected Clients: activator-dda06fbc-939d-42c9-8657-5998717df780, activator-93f84cf2-9e6a-48cb-a420-a57e5535aeb5
Taking next connection to: 49506
New client attempting to connect on port: 49740-49506
  Address = /192.168.178.33:49506
Handshake exception on socket: 49740
sbt.impl.ipc.HandshakeException: Unable to perform handshake
	at sbt.impl.ipc.Peer.handshake(IPC.scala:46)
	at sbt.impl.ipc.MultiClientServer.<init>(IPC.scala:150)
	at sbt.server.SbtServerSocketHandler$$anon$1.run(SbtServerSocketHandler.scala:43)
Caused by: java.net.SocketException: Software caused connection abort: recv failed
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.read(Unknown Source)
	at java.net.SocketInputStream.read(Unknown Source)
	at java.io.BufferedInputStream.fill(Unknown Source)
	at java.io.BufferedInputStream.read(Unknown Source)
	at java.io.DataInputStream.readInt(Unknown Source)
	at sbt.impl.ipc.Peer.receive(IPC.scala:95)
	at sbt.impl.ipc.Peer.handshake(IPC.scala:49)
	... 2 more
Taking next connection to: 49506
New client attempting to connect on port: 49741-49506
  Address = /192.168.178.33:49506
This client on port 49741 has uuid 9613a585-b887-49eb-bcbc-9e1d28e302d8 configName play-fork-run humanReadableName Play Fork Run protocolVersion 1 featureTags Vector()
Connected Clients: activator-93f84cf2-9e6a-48cb-a420-a57e5535aeb5, play-fork-run-9613a585-b887-49eb-bcbc-9e1d28e302d8
Taking next connection to: 49506
